#!/bin/sh
#
# Startup script for the Wherehoo Server
#
# chkconfig: 345 95 95
# description: Wherehoo is a location server.
# processname: whserver

# Source function library.
. /etc/rc.d/init.d/functions

# See how we were called.
case "$1" in
  start)
        echo -n "Starting WHServer: "
		export 'CLASSPATH'=/home/wherehoo/current/:/usr/local/pgsql/share/java/jdbc7.1-1.1.jar
        /usr/java/current/bin/java WHServer &
        ;;
  stop)
        echo -n "Shutting down WHServer: "
        killproc /usr/java/current/bin/java
        echo
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0

